### ISSUE TITLE
Attack definition file

### ISSUE THREAD

**Issue by alexaib2002** [alexaib2002/dam-rpg-js#14]
All game attacks should be defined on a JSON file. Structure pre-implementation, ordered by levels:

Outer dict:
- Key: `attackID` : Value: `data dict`

Data dict
- Key: `name` : Value: `attack name, could be displayed on some text dialog`
- Key `e_description` Value: `description dialog when the attack is made by enemy`
- Key `p_description` Value: `description dialog when the attack is done by player`

```
{
  "bash": {
    "name": "Bash",
    "description": "%s is suddenly bashes you!!"
  },
  "kick": {
    "name": "Kick",
    "description": "%s did a quick kick!!"
  },
  "none": {
    "name": "No attack",
    "description": "%s did nothing to defend itself!!"
  }
}
```

**Comment by Tsuki-i** [comment]
closing as issue has been implemented
