### ISSUE TITLE
Enemy definition file

### ISSUE THREAD

**Issue by alexaib2002** [alexaib2002/dam-rpg-js#15]
All existing enemies should be defined on a JSON file.

Outer dict:
- Key: `enemyID` : Value: `data dict`

Data dict:

- Key: `name` : Value: `enemy name for displaying on dialog box`
- Key `health` Value: `integer value for enemies' health`
- Key `attacks` Value: `array of available attacks. attackID must be defined on attacks.json`

```
{
  "enemy_00": {
    "name": "GenericEnemy1",
    "health": 100,
    "attacks": [
      "bash",
      "kick"
    ]
  },
  "enemy_01": {
    "name": "GenericEnemy2",
    "health": 50,
    "attacks": [
      "none"
    ]
  }
}
```

Attacks should be related to their own attack definition JSON file.

**Comment by Tsuki-i** [comment]
closing as issue has been implemented
