### ISSUE TITLE
Implement attack system logic 

### ISSUE THREAD

**Issue by alexaib2002** [alexaib2002/dam-rpg-js#7]
Logic for battle screen must be implemented, so when player selects some button, an action gets triggered.

Should be abstracted to a class. Behaviors to implement:

- [x] Attack
- [x] Health recover
- [x] Defense
- [ ] Escaping from enemy

**Comment by Tsuki-i** [comment]
added attack, health recover and defense fuctions. Escape function is WIP.

**Comment by alexaib2002** [comment]
Refactored attack, health recover and defense functions to comply with existing codebase

**Comment by alexaib2002** [comment]
Every component of battleBehaviour is implemented on #26 branch. Closing issue.
